baseURL: "https://guojiaxuan2001.github.io/"
languageCode: "en-us"
theme: "PaperMod"
title: "Kelly's Space"

params:
  homeInfoParams:
    Title: "Welcome to my world"
    Content: "Kelly"
    authorDescription: "Developer"
    info: "Welcome to my world"
    darkModeTheme: "data-dark-mode"

menu:
  main:
    - name: "Blog"
      url: "https://guojiaxuan2001.github.io/posts/"
      weight: 1
    - name: "Archive"
      url: "https://guojiaxuan2001.github.io/archive/"
      weight: 2
    - name: "Contact"
      url: "https://guojiaxuan2001.github.io/contact/"
      weight: 3
    - name: "Statistic"
      url: "https://guojiaxuan2001.github.io/xx/"
      weight: 4
